version: '3.8'

services:
  app:
    build: .
    ports:
      - 8091:8091
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/dockerdemo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: nittan
    networks:
      - my-network
    depends_on:
      - docker-mysql

  docker-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=nittan
      - MYSQL_DATABASE=dockerdemo
      - MYSQL_USER=root
      - MYSQL_PASSWORD=nittan
#      DATABASE_PORT: 3306
#      MYSQL_USER: root
#      MYSQL_PASSWORD: nittan
#      MYSQL_DATABASE: dockerdemo
#      MYSQL_ROOT_PASSWORD: nittan
    ports:
      - 3307:3306
    networks:
      - my-network
    volumes:
      - mysql-s-data:/var/lib/mysql

networks:
  my-network:
    driver: bridge

volumes:
  mysql-s-data:

